apiVersion: v1
kind: Namespace
metadata:
  name: apps

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pyapp
  name: pyapp
  namespace: apps

---

apiVersion: v1
kind: Secret
metadata:
  name: pyapp-svca-token
  namespace: apps
  annotations:
    kubernetes.io/service-account.name: "pyapp"
type: kubernetes.io/service-account-token

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyapp
  name: pyapp
  namespace: apps
spec:
  selector:
    matchLabels:
      app: pyapp
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: babbili/py-app:cfb923622
          imagePullPolicy : Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
          - containerPort: 5000
      serviceAccount: pyapp
      serviceAccountName: pyapp

---

apiVersion: v1
kind: Service
metadata:
  name: pyapp
  namespace: apps
  labels:
    app: pyapp
spec:
  type: ClusterIP
  selector:
    app: pyapp
  ports:
    - port: 80
      targetPort: 5000  

